--Total counts per invoice, stocks, customers
SELECT 
    COUNT(*) AS total_rows,
    COUNT(DISTINCT invoice_code) AS invoice_counts,
    COUNT(DISTINCT stock_code) AS stock_counts,
    COUNT(DISTINCT customer_id) AS customers_counts
FROM transformed_retail;


--Get Gross Sales, and Quantity Sold
SELECT *
FROM (
    SELECT revenue_per_unit, quantity, date_year
    FROM retail_features
)
PIVOT (
    SUM(revenue_per_unit) AS gross_sales,
    SUM(quantity) AS quantity_sold
    FOR date_year IN ('2010' AS "2010", '2011' AS "2011")
);


SELECT 
    DATE_YEAR,
    SUM(QUANTITY) OVER (PARTITION BY DATE_YEAR) AS YEARLY_TOTAL_QUANTITY,
    SUM(REVENUE_PER_UNIT) OVER (PARTITION BY DATE_YEAR) AS YEARLY_TOTAL_REVENUE,
    DATE_QUARTER,
    SUM(QUANTITY) OVER (PARTITION BY DATE_YEAR, DATE_QUARTER) AS QUARTERLY_TOTAL_QUANTITY,
    SUM(REVENUE_PER_UNIT) OVER (PARTITION BY DATE_YEAR, DATE_QUARTER) AS QUARTERLY_TOTAL_REVENUE,
    DATE_MONTH,
    SUM(QUANTITY) OVER (PARTITION BY DATE_YEAR, DATE_MONTH) AS MONTHLY_TOTAL_QUANTITY,
    SUM(REVENUE_PER_UNIT) OVER (PARTITION BY DATE_YEAR, DATE_MONTH) AS MONTHLY_TOTAL_REVENUE,
    DATE_DAY,
    SUM(QUANTITY) OVER (PARTITION BY DATE_YEAR, DATE_DAY) AS DAILY_TOTAL_QUANTITY,
    SUM(REVENUE_PER_UNIT) OVER (PARTITION BY DATE_YEAR, DATE_DAY) AS DAILY_TOTAL_REVENUE,
    DAY_OF_WEEK,
    SUM(QUANTITY) OVER (PARTITION BY DATE_YEAR, DAY_OF_WEEK) AS DAY_OF_WEEK_TOTAL_QUANTITY,
    SUM(REVENUE_PER_UNIT) OVER (PARTITION BY DATE_YEAR, DAY_OF_WEEK) AS DAY_OF_WEEK_TOTAL_REVENUE,
    TIME_PERIOD,
    SUM(QUANTITY) OVER (PARTITION BY DATE_YEAR, TIME_PERIOD) AS TIME_PERIOD_TOTAL_QUANTITY,
    SUM(REVENUE_PER_UNIT) OVER (PARTITION BY DATE_YEAR, TIME_PERIOD) AS TIME_PERIOD_TOTAL_REVENUE
FROM retail_features;

